let apartments = [
 {
    aptName:'Mountain View',
    location: 'sinkor',
    address:'14 street landside between coleman and cheesman : building with red gate',
    aptType:'condominium',
    bedrooms: 4,
    bathrooms: '3 1/2',
    leaseType: 'month to month',
    price: '$3000 per month ',
    ammenities: ['Balcony', 'Pet friendly', 'Pool', 'Onsite Laundry'],
    verified: false,
    electricity: '24 hours',
    security: '24 hours',
    water: '24 hours',
    images: ['../public/images/Building1.jpg','../public/images/Building2.jpg','../public/images/Building3.jpg',
    '../public/images/Building4.jpg','../public/images/Building5.jpg','../public/images/Building6.jpg',
    '../public/images/Building7.jpg','../public/images/Building8.jpg','../public/images/Building9.jpg'
    ]
  },
  {
    aptName:'Lib Houses',
    location: 'mamba point',
    address: '802 UN Drive: In between Mamba point Hotel and Ambassador Hotel',
    aptType:'apartment',
    bedrooms: 2,
    bathrooms: 2,
    leaseType: 'long term',
    price: '$1200 per month ',
    ammenities: ['Balcony', 'Pet friendly', 'Pool', 'Onsite Laundry'],
    verified: true,
    electricity: '24 hours',
    security: '24 hours',
    water: '24 hours',
    images: ['../public/images/Building1.jpg','../public/images/Building2.jpg','../public/images/Building3.jpg',
    '../public/images/Building4.jpg','../public/images/Building5.jpg','../public/images/Building6.jpg',
    '../public/images/Building7.jpg','../public/images/Building8.jpg','../public/images/Building9.jpg'
    ]
  },
  {
    aptName:'I Lab',
    location: 'downtown',
    address: 'camp johnson road: near the old YES Transport building',
    aptType:'condominium',
    bedrooms: 4,
    bathrooms: '3 1/2',
    leaseType: 'month to month',
    price: '$3000 per month ',
    ammenities: ['Balcony', 'Pet friendly', 'Pool', 'Onsite Laundry'],
    verified: false,
    electricity: '24 hours',
    security: '24 hours',
    water: '24 hours',
    images: ['../public/images/Building1.jpg','../public/images/Building2.jpg','../public/images/Building3.jpg',
    '../public/images/Building4.jpg','../public/images/Building5.jpg','../public/images/Building6.jpg',
    '../public/images/Building7.jpg','../public/images/Building8.jpg','../public/images/Building9.jpg'
    ]
  },
  {
    aptName:'red roof',
    location: 'congo town',
    address: 'B-89 congotown: next to the french embassy',
    aptType:'apartment',
    bedrooms: 2,
    bathrooms: '3 ',
    leaseType: 'month to month',
    price: '$2500 per month ',
    ammenities: ['Balcony', 'Pet friendly', 'Pool', 'Onsite Laundry'],
    verified: false,
    electricity: '24 hours',
    security: '24 hours',
    water: '24 hours',
    images: ['../public/images/Building1.jpg','../public/images/Building2.jpg','../public/images/Building3.jpg',
    '../public/images/Building4.jpg','../public/images/Building5.jpg','../public/images/Building6.jpg',
    '../public/images/Building7.jpg','../public/images/Building8.jpg','../public/images/Building9.jpg'
    ]
  },
  {
    aptName:'brenda place',
    location: 'sinkor',
    aptType:'room',
    address:'16 street: next to Royal hotel',
    bedrooms: 1,
    bathrooms: '1',
    leaseType: 'daily',
    price: '$10 per day',
    ammenities: [],
    verified: true,
    electricity: '24 hours',
    security: '24 hours',
    water: '24 hours',
    images: ['../public/images/Building1.jpg','../public/images/Building2.jpg','../public/images/Building3.jpg',
    '../public/images/Building4.jpg','../public/images/Building5.jpg','../public/images/Building6.jpg',
    '../public/images/Building7.jpg','../public/images/Building8.jpg','../public/images/Building9.jpg'
    ]
  },
  {
    aptName:'Taj',
    location: 'paynesville',
    address: 'old congotown backrood: next to chinese embassy',
    aptType:'condominium',
    bedrooms: 2,
    bathrooms: '3',
    leaseType: 'month to month',
    price: '$3000 per month ',
    ammenities: ['Balcony', 'Pet friendly', 'Pool', 'Onsite Laundry'],
    verified: false,
    electricity: '24 hours',
    security: '24 hours',
    water: '24 hours',
    images: ['../public/images/Building1.jpg','../public/images/Building2.jpg','../public/images/Building3.jpg',
    '../public/images/Building4.jpg','../public/images/Building5.jpg','../public/images/Building6.jpg',
    '../public/images/Building7.jpg','../public/images/Building8.jpg','../public/images/Building9.jpg'
    ]
  },
  {
    aptName:'Overview',
    location: 'sinkor',
    address: '5 street: road next to liquor store',
    aptType:'apt',
    bedrooms: 2,
    bathrooms: '3 1/2',
    leaseType: 'yearly',
    price: '$3000 per month ',
    ammenities: ['Balcony', 'Pet friendly', 'Pool', 'Onsite Laundry'],
    verified: true,
    electricity: '24 hours',
    security: '24 hours',
    water: '24 hours',
    images: ['./images/Building1.jpg','../public/images/Building2.jpg','../public/images/Building3.jpg',
    '../public/images/Building4.jpg','../public/images/Building5.jpg','../public/images/Building6.jpg',
    '../public/images/Building7.jpg','../public/images/Building8.jpg','../public/images/Building9.jpg'
    ]
  },
  {
    aptName:'Gateway',
    location: 'downtown',
    address: 'Carey and Benson street: near hotel liberia',
    aptType:'room',
    bedrooms: 1,
    bathrooms: '1',
    leaseType: 'month to month',
    price: '$50 per month ',
    ammenities: ['Balcony', 'Pet friendly', 'Onsite Laundry'],
    verified: true,
    electricity: '24 hours',
    security: '24 hours',
    water: '24 hours',
    images: ['./images/Building1.jpg','../public/images/Building2.jpg','../public/images/Building3.jpg',
    '../public/images/Building4.jpg','../public/images/Building5.jpg','../public/images/Building6.jpg',
    '../public/images/Building7.jpg','../public/images/Building8.jpg','../public/images/Building9.jpg'
    ]
  },
  {
    aptName:'derty View',
    location: 'mamba point',
    address:'Near the new US emabassy',
    aptType:'condominium',
    bedrooms: 2,
    bathrooms: '2',
    leaseType: 'long term',
    price: '$1900 per month ',
    ammenities: ['Balcony', 'Pet friendly', 'Pool', 'Onsite Laundry'],
    verified: false,
    electricity: '24 hours',
    security: '24 hours',
    water: '24 hours',
    images: ['../public/images/Building1.jpg','../public/images/Building2.jpg','../public/images/Building3.jpg',
    '../public/images/Building4.jpg','../public/images/Building5.jpg','../public/images/Building6.jpg',
    '../public/images/Building7.jpg','../public/images/Building8.jpg','../public/images/Building9.jpg'
    ]
  },
  {
    aptName:'freind View',
    location: 'congotown',
    address:'Opposite Zone 3 police station',
    aptType:'house',
    bedrooms: 4,
    bathrooms: '3 1/2',
    leaseType: 'month to month',
    price: '$3900 per month ',
    ammenities: ['Balcony', 'Pet friendly', 'Pool', 'Onsite Laundry'],
    verified: true,
    electricity: '24 hours',
    security: '24 hours',
    water: '24 hours',
    images: ['../public/images/Building1.jpg','../public/images/Building2.jpg','../public/images/Building3.jpg',
    '../public/images/Building4.jpg','../public/images/Building5.jpg','../public/images/Building6.jpg',
    '../public/images/Building7.jpg','../public/images/Building8.jpg','../public/images/Building9.jpg'
    ]
  },
]


module.exports = apartments;
